packages:
  - packages/*
  - apps/*

catalog:
  typescript: 5.9.3
  vitest: 4.0.15

overrides:
  "@modelcontextprotocol/sdk@<1.24.0": ">=1.24.0"
  body-parser@>=2.2.0 <2.2.1: ">=2.2.1"
  js-yaml@>=4.0.0 <4.1.1: ">=4.1.1"
